### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#100]
cboettig -> ropensci

**Comment by maelle** [comment]
error when trying 🤔

**Comment by cboettig** [comment]
I dunno, this one confuses me every time.  I thought appveyor didn't have a notion of organizational accounts and that we were supposed to just leave this one at an individual account because migrating it wouldn't work?  Maybe @sckott or @noamross know better?

**Comment by maelle** [comment]
I do activate ropensci/foo repos but am still confused every time 🙈

**Comment by maelle** [comment]
The problem with its not being ropensci is that if I want to re-launch or cancel a build as a contributor, I can't. Not too bad but less optimal.

**Comment by sckott** [comment]
So AFAICT if you authorize with github to create an account then that acct is attached to your github. But if you sign up with email and password then that can be managed as a sort of organization account by adding team members under Team in settings. 

I have an appveyor account under the name ropensci that i created with email/pwd login, to which maelle, noam, and mark padgham are added. it has about 25 repos or so

I could move all the repos under my github authorized acct to the email/pwd account, then folks would have access to those.
