### ISSUE TITLE
Repo status

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#102]
This is more of a codemeta question @cboettig.

https://codemeta.github.io/terms/ seems to refer to repostatus.org as a reference for the developmentStatus term.

So if I follow correctly

* Either `codemetar` should ignore any repo status badge that's not from repostatus.org e.g. ignore tidyverse badges.

* Or could codemeta developmentStatus term be "linked" to a provider so that one could use any set of repo status?

**Comment by cboettig** [comment]
yes, probably best to provide  a full URL in that field.  If a single term is used, then the assumption is that it uses the repostatus.org sense of the term.

**Comment by maelle** [comment]
ah much easier solution than having term+provider! cool. the new intern function `extract_badges` can give that easily.

**Comment by maelle** [comment]
forgot to link 2d commit https://github.com/ropensci/codemetar/commit/0b1f486034203920c877522dbfbd9753b880c466
