### ISSUE TITLE
Order of elements in codemeta.json

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#113]
Should `write_codemeta` always write elements in the same order?

Asking because some of the differences seen in https://github.com/ropensci/codemetar/pull/89/files#diff-825c48cfd9d909baadb0f1e3fdee98f1 are actually due to some elements being created later and thus not being at the same position than before.

**Comment by cboettig** [comment]
Good question! JSON-LD expects all applications to be agnostic to order (keys are unique, so every element should be referenced by key and not order number).  

That said, it might be nice visually to have a consistent and sensible default order, though I don't think it should ever be a hard standard.  We more-or-less get this by programmatically creating the codemeta.json, so I think we don't need to worry about this. so I'm happy to close this out if you are.

**Comment by maelle** [comment]
Thx! Yeah the git line by line diff is the only "problem"
