### ISSUE TITLE
Orcid

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#115]
When did they start looking like https://github.com/ropensci/codemetar/blob/master/DESCRIPTION#L22 ? Is it wanted or a side effect of my wrangling DESCRIPTION via `desc`? Sorry to only have time to notify and not solve today @cboettig

**Comment by cboettig** [comment]
good catch, that must have been an unintended side effect.  It's probably still valid R code and all so the checks don't catch that, but would look much nicer in the usual named character vector format.

**Comment by maelle** [comment]
Yeah and maybe this version wouldn't even render well on CRAN.
