### ISSUE TITLE
Blog post illustrating/promoting codemetar

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#118]
Following a discussion with `codemetar` CEO @cboettig 

Once I've started using @sckott's tool that has a copy of all ropensci repos a blog post would

* briefly present Codemeta & `codemetar`

* explain how we (plan to) use it for the registry (and pre-registry building quality checks)

* an example aimed at attracting a larger readership, using `extract_badges` over all READMEs of CRAN packages that have a GitHub repo listed under Repository in DESCRIPTION.

The title could be "Manage and promote a herd of packages with codemetar" or a better verb than promote, this verb should reflect the goal of Codemeta.

Cc @stefaniebutland, when would it fit in the blog schedule? I'm not sure I'd have written it before unconf.

**Comment by maelle** [comment]
The blog post should make clear this is all about packages _metadata_ and mention tools aimed at improving other aspects of packages such as `lintr` (+ `styler`) and `goodpractice`.

**Comment by stefaniebutland** [comment]
> Cc @stefaniebutland, when would it fit in the blog schedule? I'm not sure I'd have written it before unconf.

post-unconf I'm guessing we will have 2-3 weeks of almost exclusively unconf posts then we can fit this one in when we like

**Comment by maelle** [comment]
I'm thinking of two tech notes:
* one explaining the new packages page setup when it's finished (getting closer)
* one playing with the big codemeta.json of all packages like what @cboettig did in the vignette/article of a package (was it `codemetar`?).

**Comment by maelle** [comment]
And maybe a first one presenting #20 because if we do that on json-ld repos it's a good way to explain json-ld at the same time...

**Comment by maelle** [comment]
I think that after next release, @cboettig's whybother.Rmd would make a good basis for a short tech note.

**Comment by cboettig** [comment]
> I think that after next release, @cboettig's whybother.Rmd would make a good basis for a short tech note.

:-)

happy to work on that with you! we promised to do something like that long ago, but I feel we're only finally getting to the point where the answer is a bit more convincing.  (though would be even better if zenodo also does their integration like it says for Q3 2019 target, but at least now there's SoftwareHeritage!)  cc @mbjones

**Comment by maelle** [comment]
any news about Zenodo?

**Comment by cboettig** [comment]
Nope; still watching https://github.com/zenodo/zenodo/issues/1504 though. 👀 👀

**Comment by maelle** [comment]
Just a note on phrasing I was thinking about. codemetar converts local package metadata of the package to a given format, whilst also _enriching_ it using web data resources when online.

**Comment by maelle** [comment]
Also, it is quite obvious, but having good package metadata is good in general so the opinions giving by codemetar is not useless.
