### ISSUE TITLE
Regarding warning about installing packages (unable to access ....)

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#119]
Looks like these are the lines that trigger that

https://github.com/ropensci/codemetar/blob/4ab555a61ee42b046412089bf641f34f0e95f9de/R/guess_metadata.R#L6-L15

We should probably move these to `data_raw` instead and ship with a cached version of "available packages".  It won't be as up-to-date, but then we should probably be providing a user interface to let the user update this information anyway (or be updating it if package is loaded interactively and a network connection is available, not updating it on package *install* which is effectively what this does.

**Comment by maelle** [comment]
Aaah good catch! too bad!

**Comment by maelle** [comment]
will transform them into functions, and memoise them.
