### ISSUE TITLE
Should dependencies be listed iteratively

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#148]
Something I realized while looking at `containerit` code. Currently `codemetar` parses DESCRIPTION to find dependencies. Should it actually try and find dependencies _iteratively_, i.e. packages and system requirements of dependencies as well? What makes more sense, the current process or a more exhaustive listing of dependencies?

And if it does look for dependencies iteratively it'd look similar to `contenairit` code... should that code be depended on/copied, should it actually live in a separate package?

**Comment by cboettig** [comment]
No, I think it's sufficient to just list immediate dependencies.  The full dependency tree would often be huge!

Technically you could nest these dependencies (recall that the dependency descriptions are themselves 'codemeta' objects (`@type` `softwareApplication`, and so can have `dependency` inside them.  But also with JSON-LD you kind of get this nesting 'for free' if you have JSON-LD elsewhere that fully describes the dependencies (and you have `@id`s for all dependencies), you can have these automatically nest by using a JSON-LD frame with the only directive as `"@embed": "@always".

**Comment by maelle** [comment]
Thanks!
