### ISSUE TITLE
Onboard to rOpenSci

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#15]

**Comment by cboettig** [comment]
Submitted to onboarding, https://github.com/ropensci/onboarding/issues/130

**Comment by maelle** [comment]
I think you can close this issue 😉

**Comment by cboettig** [comment]
:rocket:

**Comment by maelle** [comment]
I forgot to _suggest_ adding the reviewers as "rev" in DESCRIPTION if they and you want.
