### ISSUE TITLE
`write_codemeta()` fails when code is not pushed to GitHub

### ISSUE THREAD

**Issue by noamross** [ropensci/codemetar#162]
I get the following error when I run `write_codemeta()` on a repository that is not a Git Repository:

```
Some elements could be improved, see our opinions via give_opinions('.')
Error in gh_process_response(raw) :
GitHub API error (404): 404 Not Found
Message: Not Found
Read more at https://developer.github.com/v3/repos#list-all-topics-for-a-repository

URL not found: https://api.github.com/repos/noamross/hello2/topics
Calls: <Anonymous> ... add_github_topics -> <Anonymous> -> gh_process_response -> gh_error
```

In this particular case, the repo *does* have GitHub URL/BugReports entries in DESCRIPTION.  This is because this is part of a general package setup script - all the files for an empty package are generated, *then* they are committed in a single commit and pushed to GitHub for the first time.   It's here: https://github.com/noamross/mkrpkg/blob/master/inst/mkrpkg.R#L127-L129

I realize this is an edge use case, so maybe it should error out, but wanted to check.

**Comment by maelle** [comment]
My fault 😱 Thanks!

I need to add a step checking the repo exists before using it for getting topics and the preferred README.

**Comment by maelle** [comment]
I think it is now solved in dev via https://github.com/ropensci/codemetar/pull/166
