### ISSUE TITLE
codemetar asks to overwrite existing pre-commit hook 

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#168]
If a user already has a pre-commit hook (i.e. from `usethis::use_readme_rmd`) codemetar asks to overwrite it.  more annoyingly, if you decline this, `write_codemeta()` throws an error instead of creating a `codemeta.json` file.  

Is there a way for these pre-commit hooks to coexist nicely?  

Alternatively, it would be good that if the user declines this, the function continues instead of throwing an error.

**Comment by maelle** [comment]
Cf https://github.com/r-lib/usethis/issues/368 too

**Comment by maelle** [comment]
@noamross added an argument to `write_codemeta` btw, so you can choose not to create a git hook (but not what you describe yet)

**Comment by maelle** [comment]
Maybe we could simply append the lines from "our" hook to the existing hook if there's one.

**Comment by maelle** [comment]
https://github.com/lorenzwalthert/precommit but not on CRAN yet
