### ISSUE TITLE
Support shields.io badges as tidyverse.org/lifecycle suggest.

### ISSUE THREAD

**Issue by katrinleinweber** [ropensci/codemetar#170]
As a follower of the above badge suggestion, I would like to see [`give_opinions(".")`](https://github.com/ropensci/codemetar/blob/7ce13ba50a439b7b9accd8b694bd486c23685384/R/give_opinions.R) recognise that and opine to `Add a status badge cf e.g repostatus.org`.

Where would be the best place to add code for detecting lifecycle / shields.io badges? At https://github.com/ropensci/codemetar/blob/7ce13ba50a439b7b9accd8b694bd486c23685384/R/give_opinions.R#L90-L96 maybe?

**Comment by maelle** [comment]
Good point! can you tell me whether the badge is present in the data.frame given by `codemetar::extract_badges`?

Would you be interested in making a PR? Note, please PR off "dev"

Then yes give_opinions would need a fix as well as https://github.com/ropensci/codemetar/blob/4bab10af15173537793ea5e93768e2098cd55b64/R/guess_metadata.R#L73 & the corresponding test https://github.com/ropensci/codemetar/blob/4bab10af15173537793ea5e93768e2098cd55b64/tests/testthat/test-guess_metadata.R#L37 incl adding an example in https://github.com/ropensci/codemetar/tree/dev/inst/examples

Related to #169

**Comment by maelle** [comment]
I'll make this update.

**Comment by maelle** [comment]
I see e.g. `[![lifecycle](https://img.shields.io/badge/lifecycle-maturing-blue.svg)](https://www.r-pkg.org/pkg/epiphy)` -- the status will be the URL, which is wrong in this case, but IMO the URL in the badge should be the definition of the status e.g. `[![lifecycle](https://img.shields.io/badge/lifecycle-maturing-blue.svg)](https://www.tidyverse.org/lifecycle/#maturing)`. I hope it makes sense?

**Comment by maelle** [comment]
PR to dev merged, please tell me if it now works for your use case @katrinleinweber 😸

**Comment by katrinleinweber** [comment]
I think it does :-)   No more `Add a status badge...`, but:

```
> codemetar::give_opinions(".")
NULL
```

How about joking about it in that situation? Like suggsted in:
