### ISSUE TITLE
Robustness at different parts of the codemeta.json creation

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#175]
`codemetar` gets data from GitHub API, soon from a csv with information about rOpenSci reviews cf #23 . 

It'd make sense to check for the presence of an internet connection, to try a few times, and to output NULLs instead of errors.

**Comment by maelle** [comment]
Also be more robust to hitting GitHub API rate limits, especially in the absence of a token.

**Comment by maelle** [comment]
* if rOpenSci review badge, rOpenSci review info gotten from a JSON on the web.
* if GitHub repo, Preferred README, and repo topics, gotten via GitHub API (`gh::gh()`) . In a `try()`.

**Comment by maelle** [comment]
@sckott have you actually observed many failures when building the registry?

**Comment by sckott** [comment]
not many no. There was that PR #247 and #236 , but those fixed now. 

The biggest thing I can think of is the keywords problem, which I don't really have any ideas how to fix since its so intermittent

**Comment by maelle** [comment]
fixed iv dev by #255
