### ISSUE TITLE
Category tags in DESCRIPTION

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#186]
I was re-reading https://juliasilge.com/blog/package-guidance/ by Julia Silge in preparation for a talk and saw

> I have since learned that there is support for some tagging architecture for packages on CRAN (for example, see [here](https://cran.r-project.org/web/packages/lfe/)) in the DESCRIPTION file using ACM, JEL, or MSC classifications. 

* Should `codemetar` digest these?
* Too bad `X-schema.org-keywords` don't appear on CRAN pages.

**Comment by cboettig** [comment]
Yeah, I discussed those with Kurt when he recommended using the X-schema.org-keywords.  Yeah, It is a pity the latter doesn't appear on the CRAN pages -- we might want to revisit that issue with CRAN at some point.

I suppose ideally codemetar would parse those classification codes and return them as schema.org/keywords or or categories, but I'm not sure they are widely used enough to merit the effort right now ;-)

**Comment by maelle** [comment]
True, they're probably _not_ used a lot. 

It'd be so cool if CRAN had tags like GitHub! 🙊
