### ISSUE TITLE
new NEWS entry about the code cleaning

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#222]
cc @hsonne

**Comment by maelle** [comment]
How about "`codemetar` code was cleaned, making it easier to understand and to contribute to. Only changes to behavior are blablabla" where blablabla is the sentence you could add @hsonne?

**Comment by maelle** [comment]
Or were you expecting more details @cboettig?

**Comment by cboettig** [comment]
nope, short-and-sweet is good.  Is there anything we can link to that nicely defines what 'clean' means?  (i.e. just to convey that this was not just running the package through `lintr` or `styler`)?

**Comment by maelle** [comment]
Good points, @hsonne maybe a reference +  a few examples of principles?

**Comment by hsonne** [comment]
I will write something and give a reference to the book "Clean Code" by Robert C. Martin

**Comment by maelle** [comment]
@hsonne
