### ISSUE TITLE
zenodo: no DOI for latest CRAN release 0.1.7

### ISSUE THREAD

**Issue by mrustl** [ropensci/codemetar#227]
@cboettig, just noticed that there is no zenodo DOI for the latest CRAN release 0.1.7 of codemetar. 

You are not using the  automatic integration of GitHub - Zenodo integration (https://guides.github.com/activities/citable-code/) due to the chicken-egg problem (https://github.com/ropensci/codemetar/issues/135#issuecomment-385026553) right?

**Comment by cboettig** [comment]
@mrustl Thanks!  No, in this case I just hadn't pushed the tag yet!  We've opted in to the integration since the good should not be the enemy of the best.  Should be there now.  


Version 0.1.7 doi:10.5281/zenodo.2598516

**Comment by mrustl** [comment]
Thanks. Could you also add the ORCIDs as metadata on Zenodo for the authors/contributors?

That would be great!

**Comment by cboettig** [comment]
good call, yeah I should do that.  Lars tells me that one day those things will be imported automatically from https://github.com/ropensci/codemetar/blob/master/codemeta.json but we're not there yet...

**Comment by mrustl** [comment]
Hauke, Boetti muss nochmal ran  (siehe unten)

Du bist übrigens Nummer 3 Author auf Zenodo….
https://zenodo.org/record/2598516

Hab schon in FAKIN reingehauen und sollte auch in 10 Minuten up-to-date sein:
https://kwb-r.gitlab.io/fakin/publication/codemetar/

Von: Carl Boettiger [mailto:notifications@github.com]
Gesendet: Dienstag, 19. März 2019 19:11
An: ropensci/codemetar
Cc: Michael Rustler; Mention
Betreff: Re: [ropensci/codemetar] zenodo: no DOI for latest CRAN release 0.1.7 (#227)


good call, yeah I should do that. Lars tells me that one day those things will be imported automatically from https://github.com/ropensci/codemetar/blob/master/codemeta.json but we're not there yet...

**Comment by maelle** [comment]
@cboettig what is needed here?

**Comment by cboettig** [comment]
The Zenodo importer still doesn't yet read codemeta, so we'd have to get codemetar to spit out a valid .zenodo.json file , and need to manually update previous releases to add any  additional metadata like ORCID ids by hand.  

Since we have a DOI for the latest CRAN release at very least, I think we can close this out though.  Patching past metadata and automating Zenodo integration are separate issues.
