### ISSUE TITLE
Warnings on extraction of orcid when composite comment

### ISSUE THREAD

**Issue by billy34** [ropensci/codemetar#229]
Hello
In my package I have for one author the following comment
```
person(......, comment=c(ORCID="....",site="http://...."))
```
When I call `create_codemeta` I get ,along with the result, warning messages
```
Warning messages:
1: In if (grepl("orcid", comment)) { :
  the condition has length > 1 and only the first element will be used
```
It seems there's a missing  `any` in the test near line 158 in `parse_people.R` 
```
if(any(grepl("orcid",comment))) {
  return(comment[grepl("orcid",comment)])
}
```

**Comment by maelle** [comment]
good catch, thanks, could you make a PR to the dev branch?

**Comment by billy34** [comment]
PR check failed because of another unrelated bug in `test-write_codemeta.R` in test **We can deduce relatedLink from installed pkg**.

URL in `usethis` DESCRIPTION file has been recently modified and is no longer containing a single URL and so breaks the expect_equal.

As I don't know how you want to test your package I won't go any further in fixing it

**Comment by maelle** [comment]
Yep, I'll fix that tomorrow, I also need to merge master into dev, my fault, sorry. If I get it all mixed up I will manually add your edits and write your name in NEWS.

**Comment by maelle** [comment]
And thanks a ton for the PR!!
