### ISSUE TITLE
write_codemeta() writes pre-commit hook without user consent 

### ISSUE THREAD

**Issue by RLumSK** [ropensci/codemetar#240]
## Background

Today I tried the 'codemetar' package for the first time, but I stopped using it for the moment due to the issue reported earlier. Anyway, I had tried `write_codemeta()` and decided to wait for the fix. Later, when I worked on the package for which I had tested 'codemetar' and tried to commit the changes, I got a bizarre git message, telling me that my codemeta.json is not up-to-date. This message was surprising since I could not use 'codemetar' for the moment and thus here was no *.json file. It took me a while to figure out that `write_codemeta()` had created a pre-commit hook in my `.git` folder. 

## Suggestion 

I understand the reason for the hook, it is a reasonable idea, but it should be implemented differently. When using `write_codemeta()` that last thing I did expect to happen was that the package makes, by default changes in my git environment. From my perspective, this is not covered by the CRAN policy, for a good reason (somehow similar to the issue given reason for my PR https://github.com/ropensci/codemetar/pull/239) 

I suggest that the default option for the argument `use_git_hook`  should be `FALSE` not `TRUE` (current setting).

**Comment by cboettig** [comment]
Yup, :100:% with you on this.   Want to send a PR altering the default to FALSE, along with the documentation etc?

**Comment by RLumSK** [comment]
Sure, I am happy to help (also for the other PR).

**Comment by RLumSK** [comment]
Done with #239
