### ISSUE TITLE
why bother creating a codemeta.json for your package

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#252]
This should be added to the docs.

@cboettig would you mind drafting an answer? :slightly_smiling_face: 

At the moment in the dev guide we have " as it gains popularity the JSON metadata of your package might be used by third-party services, maybe even search engines.". I imagine two other reasons
* write_codemeta() calls give_opinion() which helps you have perfect metadata.
* if everyone starts adding a codemeta.json it'll gain popularity.

**Comment by cboettig** [comment]
How's this?  

> R packages encode lots of metadata in the `DESCRIPTION` file, `README`, and other places, telling users and developers about the package purpose, authors, license, dependencies, and other information that facilitates discovery, adoption, and credit for your software.  Unfortunately, because each software language records this metadata in a different format, that information is hard for search engines, software repositories, and other developers to find and integrate.
> 
> By generating a `codemeta.json` file, you turn your metadata into a format that can [easily crosswalk](https://codemeta.github.io/crosswalk) between metadata in many other software languages.  CodeMeta is built on [schema.org](https://schema.org) a simple [structured data](https://developers.google.com/search/docs/guides/intro-structured-data) format developed by major search engines like Google and Bing to improve discoverability in search.  CodeMeta is also understood by significant software archiving efforts such as [Software Heritage](https://www.softwareheritage.org/) Project, which seeks to permanently archive all open source software.  

(It's a pity Zenodo.org support for codemeta.json still hasn't materialized, but Software Heritage bit is significant.  Not sure if it's necessary to unpack "discovery, adoption, and credit" more?

**Comment by maelle** [comment]
Thanks a ton!

Does Software Heritage crawl GitHub? And e.g. GitLab?

**Comment by maelle** [comment]
can we show an example of a software with a codemeta.json, and that software in Software Heritage database? Or maybe a link to Software Heritage's mention of codemeta if there's such a mention on their website?

**Comment by maelle** [comment]
https://docs.softwareheritage.org/devel/swh-deposit/metadata.html

**Comment by maelle** [comment]
https://www.library.caltech.edu/news/enhanced-software-preservation-now-available-caltechdata

**Comment by maelle** [comment]
fixed in dev
