### ISSUE TITLE
Auto-generated pre-commit hook makes commit fail

### ISSUE THREAD

**Issue by ms609** [ropensci/codemetar#254]
I've used codemetar with a number of packages, and for each one the pre-commit hook seems to cause an error.

When I attempt to commit changes using Github Desktop on Windows 10, I receive:

_Commit failed - exit code 1 received, with output: 'error: cannot spawn .git/hooks/pre-commit: No such file or directory'_

The only solution I've found to this has been to navigate to the `.git` folder and delete the pre-commit hook.

**Comment by maelle** [comment]
Thanks! Yes we need to overhaul the pre-commit hook. :grimacing: 

In the meantime in the dev version (`remotes::install_github("ropensci/codemetar", ref = "dev")`) there's the `use_git_hook` argument for `write_codemeta()`, that you can set to FALSE.

**Comment by maelle** [comment]
@ms609 have you gotten this issue with other git hooks e.g. the one that `usesthis::use_readme_rmd()` produces (don't try it in a project with a codemetar git hook, they don't cohabit well)?

And, easier to check, does it happen if you try to commit via RStudio or a command line?

I've seen https://github.com/desktop/desktop/issues/5036

**Comment by ms609** [comment]
Thanks for the link!  Here's what I tried:

- Dev version installed (`remotes::install_github("ropensci/codemetar", ref = "dev")`)
- Run `codemetar::write_codemeta()`
- From command line, run `git commit .Rbuildignore -m "codemeta.json"` (**success!**)

Then:
- Add "C:\Program Files\Git\bin" to the system PATH environment variable (per https://github.com/desktop/desktop/issues/5036)
- Restart Github Desktop
- Attempt commit from within Github Desktop
- **Success!**

**Comment by maelle** [comment]
Awesome! Thanks for the report!
