### ISSUE TITLE
Are the articles still relevant?

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#260]
I guess so?

We might want to tweak the navbar settings so that they don't appear under "Articles" but rather something called "Advanced"?

**Comment by cboettig** [comment]
:+1:   I agree the articles aren't particularly helpful to most users.  (Particularly given that the articles are mostly JSON-LD tutorials).  Notably, most of the articles written for users/developers *consuming* `codemeta.json`, and it's not clear that there is much demand for that.  Anyway, segmenting them off in an `Advanced` or `processing codemetar data` section or something similar probably makes sense.  

The "Codemeta Intro" one might be the exception(?), as it is basically a longer version of the README and includes some useful background links.  But happy to go with your call on this one

**Comment by maelle** [comment]
Yes, the current intro vignette has been renamed in dev so would appear under "Get started".
