### ISSUE TITLE
can/should we remove the stringi dependency

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#262]
@cboettig it's only used in https://github.com/ropensci/codemetar/blob/929a41af1d2005ab8264a63b3f140a82749e84f9/R/parse_citation.R and the package isn't a light dependency?

**Comment by cboettig** [comment]
True, but on the flip side I think there's a high probability many users have stringi already installed, and it's probably going to remain pretty stable at least.

**Comment by maelle** [comment]
ok, so less a priority, maybe for 0.2.0!

**Comment by maelle** [comment]
well I'll try removing it and if it's quick I'll do that.

**Comment by maelle** [comment]
closed by #266
