### ISSUE TITLE
commit hook thoughts

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#267]
I'm wondering whether we should ditch the commit hook and instead have a "workflow" vignette documenting how to keep codemeta.json up-to-date depending on people's workflows?

* we could point to https://github.com/lorenzwalthert/precommit and provide an git hook for codemeta.json https://github.com/lorenzwalthert/precommit/issues/51

* we could show an example of a GH action cf #251 

* we could recommend to check codemeta.json at each release.

At the same time, I guess ensuring codemeta.json is up to date can be considered as one of the roles of this package...

Thoughts @cboettig? (and anyone with an opinion!)

**Comment by maelle** [comment]
cc @Bisaloo

**Comment by maelle** [comment]
also cc @noamross because of #165

**Comment by Bisaloo** [comment]
I for one hate pre-commit hooks. It keeps nagging me and breaking my workflow while I'm still tidying things up, before I'm even thinking about pushing. Maybe my workflow is unusual? I often rebase / re-order / squash commits before pushing / merging.

I always end up deleting the pre-commit hook. If you really like the hook, maybe a pre-push hook would be better (at least for my workflow).

Otherwise, I like your two other options way better than the hook!

**Comment by maelle** [comment]
Thanks! The problem if we only suggest different methods is that more users might forget to update codemeta.json (because they'd use none of the methods since none of them is forced on them :-)).

**Comment by maelle** [comment]
Another solution that one could propose is to update the codemeta.json in the same system updating the pkgdown website (e.g. Travis deploy).

**Comment by Bisaloo** [comment]
Regarding:

> we could recommend to check codemeta.json at each release.

Maybe this could be added as a check to `devtools::check()`? Not sure how this would work but I guess it should be possible

**Comment by Bisaloo** [comment]
> Thanks! The problem if we only suggest different methods is that more users might forget to update codemeta.json (because they'd use none of the methods since none of them is forced on them :-)).

Yeah, makes sense... On the other hand, if users end up deleting the hook (or using `use_git_hook = FALSE`) because they find it too annoying, you have the same issue.

**Comment by maelle** [comment]
> Maybe this could be added as a check to devtools::check()? Not sure how this would work but I guess it should be possible

At least for rOpenSci packages we could make a wrapper for devtools::check() in rodev but then I'm not sure everyone would remember to use it. :grin:

**Comment by maelle** [comment]
wait that check is _already_ in devtools! I had forgotten about it!

**Comment by cboettig** [comment]
👏 yes!  Very much in favor of ditching the commit hook and documenting a few possible workflows (like GH actions or commit hooks) instead.
