### ISSUE TITLE
document the importance of the internet connection to create codemeta.json

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#270]
No connection -> less data.
Poor connection -> very slooow (ask me how I know).

**Comment by Bisaloo** [comment]
Oooh, so this was the source of my problems? I have a good connection at work but I'm guessing some requests were blocked due to the network configuration. And `write_codemeta()` just kept hanging for literally hours... Would it be worth adding a timeout to the requests?

In my opinion, it would be useful if said documentation specified which websites/URL are queried, and what for.

**Comment by maelle** [comment]
yes and yes, good points!

**Comment by maelle** [comment]
Keeping notes here

The package queries

* `utils::available.packages()` for CRAN and Bioconductor packages (no timeout parameter?)

* GitHub API if it finds a GitHub repo URL in DESCRIPTION or as git remotes. GitHub API is queried to find the preferred README, and the repo topics. If you use codemetar for many packages having a GITHUB_PAT is better.

* R-hub sysreqs API to parse SystemRequirements.

**Comment by maelle** [comment]
Reg timeout. I don't understand why the requests don't fail since @jeroen said curl has a default timeout of 10 seconds. I have trouble debugging this.

To set the timeout and other useful options (Jeroen mentioned https://curl.haxx.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html, https://curl.haxx.se/libcurl/c/CURLOPT_LOW_SPEED_LIMIT.html, https://curl.haxx.se/libcurl/c/CURLOPT_LOW_SPEED_TIME.html) one needs to create a handle https://jeroen.cran.dev/curl/articles/intro.html#setting-handle-options

Currently the call GitHub API uses `gh::gh()` and the call to sysreqs uses `jsonlite::fromJSON()`, I don't think one could set the options without removing them.

**Comment by maelle** [comment]
`available.packages()` uses `download.file()`.

**Comment by Bisaloo** [comment]
I wonder if this should also be documented via `message()`s in `write_codemeta()` :thinking: (possibly controlled by a `verbose` boolean argument). 

It would be useful for users who don't necessarily read the vignette and it would help pinpoint the problematic domains when working with an annoying firewal

> Fetching online data from CRAN... :heavy_check_mark: 
> Fetching online data from sysreqs API...

**Comment by maelle** [comment]
Excellent idea! I'll work on that.
