### ISSUE TITLE
Documentation for `codemeta_branch` option?

### ISSUE THREAD

**Issue by jonkeane** [ropensci/codemetar#295]
I noticed that there is an option `codemeta_branch` that lets [one specify which branch name](https://github.com/ropensci/codemetar/blob/master/R/guess_github_metadata.R#L62) to use for the `codemeta.json` file. This is really great, though I noticed it doesn't appear to be documented anywhere. 

I'm happy to send a PR describing its use, but wanted to make sure that it wasn't being hidden for a reason.

**Comment by maelle** [comment]
Oooh I had forgotten about this (the option, codemetar's needing some sort of default branch) and it's a good catch these days! A PR would be welcome, thanks a lot.

I wonder whether we should also add a call to the API to get the default branch, might be user-friendlier.

**Comment by jonkeane** [comment]
I can look into adding a call in there too, I agree that would be even better than needing to specify an option. Would we want it to get and use the branch of the checkout that it is being run against, or get the default for the whole repo? I could see arguments for both depending on how one is deploying the codemeta file.

**Comment by maelle** [comment]
Ah! Good question. @cboettig What do you think?

**Comment by cboettig** [comment]
happy to follow your lead.  

my own instincts are more towards separation of the logic between codemeta and the details of version control system entirely, but I suppose that's what `metar` or minimeta or whatever we call it is for.  But since this coupling (i.e. assuming project is a git repo, etc) is built into codemetar already, I guess either is fine here.

**Comment by maelle** [comment]
Would it be ok to just remove the option?

**Comment by jonkeane** [comment]
Thinking a bit more on this, I think it probably should be whichever branch is default on the git(hub) repository for a few reasons:

* If one had to pick a single branch, the default branch is the most logical choice 
* Referring to the current git(hub) branch could lead to spurious conflicts conflict between branches where codemeta.json has been updated only to add the current branch and the default branch where that is the name.

Though I can see arguments for wanting each branch to have a codemeta.json that reflects the branch itself as well! I'm happy to leave this be for now, and only document the option that's already available. I think having the option available is a very good thing since it let's one change what that branch is away from a hard coded default (in my cause, my default branch is `main` so I want to reference that).

**Comment by maelle** [comment]
@cboettig released 0.1.9 in a hurry (codemetar had been taken off CRAN :cry: ) so adding this to the next milestone.

@jonkeane a docs PR would be appreciated. Others will probably switch from master so that's important indeed.
