### ISSUE TITLE
guess_fileSize() does not handle regexp like ^docs$

### ISSUE THREAD

**Issue by ThierryO** [ropensci/codemetar#299]
`files` in this [line](https://github.com/ropensci/codemetar/blob/d5651a45d029a5894c5047dc0b514e45235904ce/R/guess_other_metadata.R#L68) contains the full path, hence `^` fails as it is should be relative to the root of the package.

Unlike R CMD build, it doesn't handle folder names. IMHO `^docs$` should ignore only the `docs` folder at the root of the package and all its files.

**Comment by maelle** [comment]
Thanks, good catch too, and same question, any interest in doing a PR? (no worries if not, but I prefer knowing before diving into it myself :slightly_smiling_face: )

**Comment by ThierryO** [comment]
I'll start working on this PR first. Then on #298.
