### ISSUE TITLE
rm Appveyor and Travis CI

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#308]

**Comment by maelle** [comment]
cc @cboettig I think you have control over them, I can't access Appveyor for instance. It'll make PRs cleaner to de-activate Appveyor and Travis.

**Comment by maelle** [comment]
:wave: @cboettig

**Comment by cboettig** [comment]
@maelle yeah, I'll take a look, annoying things to deactivate. Travis.org itself is deactivated today, `codemetar` doesn't show up in my `cboettig` account, it's on the ropensci account but don't see how to deactivate it.  I deleted appveyor.

**Comment by cboettig** [comment]
p.s. we should remove the badges for these from the README as well
