### ISSUE TITLE
Please correct before 2021-05-15 to safely retain your package on CRAN.

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#310]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_codemetar.html>.

Please correct before 2021-05-15 to safely retain your package on CRAN.

It seems we need to remind you of the CRAN policy:

'Packages which use Internet resources should fail gracefully with an informative message
if the resource is not available or has changed (and not give a check warning nor error).'

This needs correction whether or not the resource recovers.

The CRAN Team

See https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/codemetar-00check.html

**Comment by maelle** [comment]
one more test to skip on CRAN then?

Related #286

**Comment by cboettig** [comment]
yup. do you have a moment for a quick PR?

**Comment by maelle** [comment]
not before next week, sorry.

**Comment by maelle** [comment]
Changes I made

* documenting the breaking changes of `write_codemeta()`
* converting tests to testthat third edition to be able to use snapshot tests (removed all occurrences of deprecated `context()`, converted `expect_is()` to `expect_type()`/`expect_s3_clqass()`). 
* modified the tests for `write_codemeta()` to actually make them tests for `create_codemeta()`, with a snapshot
* added a  snapshot test for `write_codemeta()`
* skipped all online tests, checked via turning wifi off. All tests that are skipped on CRAN are skipped if offline.

What's needed
* finishing #305 by @mpadge, I am just not sure whether it's ok to simply re-use rprojroot code?
* then merging the PR from dev to master
* then `usethis::use_release_issue()` checklist.

**Comment by maelle** [comment]
checklist in  #311
