### ISSUE TITLE
GHA is not recognized as CI by codemetar

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#314]
But actually, why do we store info about CI in codemeta.json @cboettig?

**Comment by cboettig** [comment]
ha, good point. I think `codemetar` should accept any link there.

`codemeta.json` includes CI information as (optional) metadata in case it is applicable to some use cases.  For example, an aggregator may use that information to detect and display badges, or use it as a proxy for quality (search for software to read json in R that uses CI in the development.)  

More broadly,  any information that the developer chooses to display in 'badges' in a README, say, is metadata about the software, and the fact that it is in a badge indicates (to me at least) that the developer chose to highlight that specific metadata for reasons.  Obviously there will always be badges we don't express, but CI is perhaps the single most common badge to capture, so it seems worth indicating the CI link in a machine-readable, platform agnostic format as an option. 

OTOH,  continuous integration is one of ~ 10 fields that are in codemeta but not in schema.org; nor is it in most of the other software metadata 'standards' (which mostly pre-date Travis-style CI anyhow).  For the sake of alignment as pure schema.org I'd be happy omit CI and the other codemeta-only terms.

**Comment by maelle** [comment]
Ok, thanks, so in a future version these badges should be extracted too, at least it doesn't hurt. :thinking:
