### ISSUE TITLE
Wrong parsing of meta$ tags on CITATION

### ISSUE THREAD

**Issue by dieghernan** [ropensci/codemetar#321]
See https://github.com/cboettig/codemeta/issues/7 and PR https://github.com/cboettig/codemeta/pull/9

The current implementation on {codemetar} fails to read some CITATION files. This is due to the `meta`  parameter used here:

https://github.com/ropensci/codemetar/blob/adc7868453c31c3868e21295f8c88f5e4e3ad169/R/parse_citation.R#L158-L165

So only the "Encoding" is used. on `utils::readCitationFile(citation_file, meta = meta)`.

 In some other CITATION files the use of `meta$` tags cab be quite extensive, see CITATION of {rmarkdown} where authors, year and title makes use ot the `meta$` approach. These tags are not found since they haven't been provided on the `meta` parameter. See {rmarkdown}:

https://github.com/rstudio/rmarkdown/blob/eaf6efc3fe6d39373ae0cee7ce3a034119bb47f5/inst/CITATION#L3-L19

When parsing directly the package it is fine, as you use `citation(pkg)` that already takes care of this, but on in-development packages the `meta` information should be extracted from DESCRIPTION.

cc: @cboettig @dpprdan @maelle

**Comment by dpprdan** [comment]
Since this is fixed in {codemeta} now, this will most likely be fixed here as well once #319 is addressed. 

Tagging previous items that led to the current implementation for reference: #238, #241

**Comment by cboettig** [comment]
Yup, though `codemetar` needs to be patched to re-import from `codemeta` now that the latter is on CRAN.

**Comment by dieghernan** [comment]
Good then. May I suggest to pin issue #319 and maybe add a "help needed" label? That would highlight that issue to potential contributors.

It would be great also if you provide a minimal roadmap on the issue, to track potential contributions and improvements.
