### ISSUE TITLE
README suggests installing from CRAN

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/codemetar#325]
But it's apparently not available

```r
> install.packages("codemetar")
Warning in install.packages :
  package ‘codemetar’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> 
```

I can install from GitHub, but seems odd to me that the README has instructions that aren't valid.

**Comment by adamhsparks** [comment]
Additionally the instructions for installing using _remotes_ fails.

```r
> remotes::install_github("ropensci/codemetar", ref = "dev")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref dev

  Did you spell the repo owner (`ropensci`) and repo name (`codemetar`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
 ```

Removing, `ref = "dev"` allows the installation to continue

**Comment by maelle** [comment]
Thanks!

@cboettig should we
- retire the dev branch usage for good?
- recommend using the R-universe ropensci repo in installation instructions?

**Comment by cboettig** [comment]
thanks @maelle.  I think both of these are good suggestions.  

additionally I obviously need to send this back to CRAN, but haven't had a chance to swap in `codemeta` as the underlying dependency

**Comment by bretsw** [comment]
> Thanks!
> 
> @cboettig should we
> 
>     * retire the dev branch usage for good?
> 
>     * recommend using the R-universe ropensci repo in installation instructions?

Looks like the dev branch has been deleted, but note that this means that neither option for installation currently works (see https://github.com/ropensci/codemetar/blob/master/man/rmdhunks/install-instructions.Rmd)

**Comment by maelle** [comment]
Oops, good catch @bretsw! I have now merged my own PR so the README features updated instructions.
