### ISSUE TITLE
investigate encoding issues from CITATION parsing

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#44]
https://github.com/ropensci/osmdata/issues/109

**Comment by mpadge** [comment]
any further insights here @cboettig? nudge, nudge

**Comment by cboettig** [comment]
@mpadge Thanks for the nudge.  Apparently `utils::parseCitation` wants to use whatever encoding is declared in the DESCRIPTION file, if given.  In wrapping that I wasn't passing `parseCitation` the optional DESCRIPTION meta.  Commit above should fix this.

**Comment by mpadge** [comment]
Great @cboettig, thanks! An easy fix after all
