### ISSUE TITLE
Embed Codemeta JSON-LD in README

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#46]
Codemeta information should be embedded in README output

Add a function that could be called invisibly (i.e. `echo=FALSE, results="asis"`) in the README.Rmd which would embed the codemeta information inside  `<script>` HTML element.  This way the information could be discovered by Google etc when the package is built on CRAN and/or a pkgdown website.

**Comment by maelle** [comment]
Are there cases when codemeta information would include information read from the README in particular badges (e.g. status badges, status being stable, deprecated etc.)? Maybe/probably not but if it happened, it'd be problematic. 😉

**Comment by maelle** [comment]
Actually I see there's a term for development status in codemeta.

**Comment by maelle** [comment]
Last blurb here, in the case when info from the README would be used to update codemeta, then the function displaying it in the README could first update the codemeta information, so knitting the README would both knit the README and update the codemeta information?

**Comment by cboettig** [comment]
One could put `codemetar::write_codemeta()` in an invisible (e.g. `include=FALSE`) chunk at the end of a `README.Rmd`....

**Comment by maelle** [comment]
and mention it in the doc of the function that'd do the README-printing. :-)

**Comment by maelle** [comment]
the README is often .Rbuildignored

**Comment by maelle** [comment]
Another drawback: when a pkg has a pkgdown website I tend to have a README.md, no Rmd

**Comment by cboettig** [comment]
Right, I think I was thinking this would be useful merely to get the info into pkgdown, but like you say, it would probably be better to do that as a PR to pkgdown directly.  Adding it to the readme.md directly would be something of an uglier hack; you don't really want that in the readme.
