### ISSUE TITLE
Help to add Github topics?

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#49]
Sorry if I've missed this in the docs! I was wondering whether it'd make sense to have a function that'd use the topics defined in the codemeta.json to populate Github topics (https://developer.github.com/v3/repos/#list-all-topics-for-a-repository & https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository)? And whether such a function should live in this package?

**Comment by cboettig** [comment]
ooh, that's a good idea.  Certainly could live here, though we might have enough scope for a separate package to do that and probably other related tasks requiring the gh api.  (I'm on a 'more small focused packages with few dependencies' kick at the moment)

**Comment by maelle** [comment]
Not sure what else would go in a separate package? That said, it could be a function in a package helping with aligning all onboarded packages.

I've just realized there could be a function setting the repo description and homepage for all repos lacking one. https://developer.github.com/v3/repos/#edit (it is a pet peeve of mine to have to scroll down to see what a repo is about). So two function ideas, now I agree with "enough scope for a separate package"! 😁

**Comment by maelle** [comment]
Reg repo description and URL, `usethis` has a function for that, `use_github_links()`.

**Comment by maelle** [comment]
If having topics in DESCRIPTION/codemeta becomes more prevalent, `use_github_topics()` could be suggested to `usethis` rather than a dedicated rOpenSci package?

**Comment by maelle** [comment]
Reg. stale issues (don't worry I'll soon create a dashboard repo but wanted to answer on that point) I think it should be linked to having standard issue labels across rOpenSci repositories. A worrying stale issue is one without a label or with a bug label, while an enhancement issue can be open for a while.

**Comment by maelle** [comment]
[Dashboard repo](https://github.com/ropenscilabs/t-437)
