### ISSUE TITLE
Framing & schema analogies

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#53]
The validation vignette points readers to the official JSON-LD framing documentation, while some of them might need a more intro-level documentation. I know I did. 😸 When googling "JSON-LD framing" all I could find were [these](http://manu.sporny.org/2011/semweb-problems-1/) [posts](http://www.carlboettiger.info/2017/05/17/json-ld-framing-strategy/) that helped because their authors were at the beginning of their "framing journey". 😉 But I did not find any real beginner-friendly intro.

I also struggled with frame vs. schema but was helped by @cboettig's explanation [here](https://github.com/ropensci/roregistry/issues/5#issuecomment-363164389) and [here](https://github.com/ropensci/codemetar/issues/3#issuecomment-292031044).

So I've thought of an analogy/several analogies that I tested on @annakrystalli (thanks, Anna!). I'm not sure where they could live but they could in any case be linked from the validation/parsing/framing vignette.

A _frame_ is like a grocery list. Say you want vanilla yoghurt. Depending on the supermarket it can be in the dairy/yoghurt aisle or in the dairy aisle or, weirdly, in a vanilla aisle (different levels of nesting/organizations). Your frame/grocery list just says "vanilla yoghurt" and your personal shopper `jsonld::jsonld_frame` finds vanilla yoghurt for you no matter the supermarket/the level of nesting/organization.

Anna said that URIs are barcodes!

I'm not sure what not setting explicit to FALSE would be. A hungry personal shopper who'd bring you many more things than what you said you needed?

A _schema_ is a floor plan for a supermarket, and a validator is a manager who checks that products are in their place based on that floor plan.

**Comment by cboettig** [comment]
How'd I never reply to this?  whoops.

Hmm, metaphors are tricky, lemme try something more literal.

Let's say a bunch of people want to share some data, say, describing software they wrote.  And another bunch of people want to build apps that consume this data.  How could that work?

Well, we could tell those writing the data that they all must use R `DESCRIPTION` file formats, even if the software is python, ruby, etc.  That's a *schema*, and if everyone uses the same schema for this kind of data, than the app developers need to know only how to parse `DESCRIPTION` files and nothing else.  Everything is good, but a bit draconian:  both the app developers and the users may not like DESCRIPTION files, and may have preferred formats and fields they want to use.  

A frame is a (partial) solution to this.  Each app developer can specify their own frame, which says what they want the data to look like.  For instance: `explict=TRUE` means "only give me the terms I explicitly ask for in my frame", while `explicit=FALSE` means: I didn't ask for `schema:license` field, but I see you are telling me a `schema:license`, so I'll take it!   Frames can also control the degree of nesting (too a point -- they cannot alter the "semantic meaning" of the data; i.e. mathematically speaking: the data is technically a "graph", JSON is a "tree", any given graph can be 'rooted' by different nodes to get you different "tree" representations which all correspond to the same graph -- yeah, that's complicated and not super useful, I know).

**Comment by cboettig** [comment]
@maelle whoops, feel free to re-open if it would be helpful, I'm just trying to catch up on stale issues

**Comment by maelle** [comment]
Thanks for the answer and no need to re-open! I'd know it's here somewhere if I write something about this one day.
