### ISSUE TITLE
adopt usethis:use_lifecycle badges

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#54]
Currently uses stability badges for package status, http://tidyverse.org/lifecycle badges probably a better fit!

**Comment by maelle** [comment]
@sckott said you all chose repostatus.org in Vancouver for rOpenSci packages, so will `codemetar` keep using them?

**Comment by cboettig** [comment]
Yes, we agreed to stick with repostatus.org.  Arguable codemetar should be able to identify any of the badges out there and add the full badge URL as the `developmentStatus` property, but for now I think we'll just leave it as is parsing only repostatus.org vocab, (which is what codemeta spec also recommends: https://codemeta.github.io/terms/#codemeta-terms)

**Comment by maelle** [comment]
Now `codemetar` can agnostically deal with both lifecycle and repostatus badge cf #102
