### ISSUE TITLE
rev role in package-level documentation

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#62]
In the package-level documentation, the role "rev" doesn't seem to be translated. https://github.com/ropensci/codemetar/blob/master/man/codemetar-package.Rd#L51

I'm pretty sure it's not a problem in this package, but where does it come from? Have only looked quickly at `roxygen2` and couldn't see anything amiss.

**Comment by maelle** [comment]
I've now installed `roxygen2` dev version and look, I solved the issue and created another one :joy: 

![image](https://user-images.githubusercontent.com/8360597/38354074-960e4edc-38b8-11e8-8aa2-7738d4ed2708.png)

**Comment by maelle** [comment]
Related issue https://github.com/klutometis/roxygen/issues/727

Will update this package doc here by hand 🙈

**Comment by cboettig** [comment]
you rock

**Comment by maelle** [comment]
* doc correct in dev

* `roxygen2` bug fixed in Jim Hester's branch https://github.com/klutometis/roxygen/pull/731
