### ISSUE TITLE
Use the sponsor term for rOpenSci?

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#65]
I'm not sure whether this should be discussed here or in ropensci/onboarding-meta. I think rOpenSci contribution to software should be reflected no matter how the package entered the suite.

What's already done/discussed in this repo and elsewhere

* Having the reviewers as authors in #45 and [this blog post](https://ropensci.org/blog/2018/03/16/thanking-reviewers-in-metadata/)

* Listing the review (I guess thanks to the review badge) in #23 

New proposal: when "ropensci" is in the GH URLs, add rOpenSci as sponsor? 

* For onboarded packages we should have authorship of reviewers with a link to the review (if the authors and the reviewers agree), review metadata via the peer-review badge (compulsory), and then rOpenSci as sponsor.

* For packages contributed by staff, rOpenSci would be both [a funder](https://github.com/ropenscilabs/rodev/issues/9#issuecomment-378636650) and a sponsor.

* For packages added to the suite pre-onboarding times, rOpenSci would also be a sponsor.

* Unconf and other draft packages living in ropenscilabs wouldn't be "sponsored" as long as they live in ropenscilabs.

I know that this is a very specific feature but after all `codemetar` is an rOpenSci package now. 😉 To make it more generalizable one could imagine having a crowd-sourced list of organizations that should be listed as sponsors depending on the GH URLs, well crowd-sourced by GH organization admins.

**Comment by maelle** [comment]
As a side-note, I think CRAN doesn't check a package source is actually located at its URL? So in theory I could lie there and have rOpenSci listed as a sponsor 🤔

**Comment by cboettig** [comment]
Thanks, yeah, we should definitely address this.  

Worth discussing, but I don't think `sponsor` is the right property to describe the relationship of packages that are on `ropensci` GitHub.  http://schema.org/sponsor defines sponsor as: 

> A person or organization that supports a thing through a pledge, promise, or financial contribution. e.g. a sponsor of a Medical Study or a corporate sponsor of an event.

For funder, I there's potentially some ambiguity here as well -- for instance, is rOpenSci the funder or is Helmsley the funder?   Note that http://schema.org/funder is defined to be a type of `sponsor`, so anything listed as a funder is by definition also a sponsor.  

I believe we discussed using the term http://schema.org/isPartOf to describe the relationship of R packages that are part of rOpenSci, e.g. 
https://github.com/ropensci/codemetar/blob/f35829a8f6c5e131a308ed1bd87249d2af0b5afa/DESCRIPTION#L49 

which creates the line:

https://github.com/ropensci/codemetar/blob/f35829a8f6c5e131a308ed1bd87249d2af0b5afa/codemeta.json#L272

**Comment by maelle** [comment]
I like that! So it's already handled and i should close this?

**Comment by maelle** [comment]
Oh so would it make sense to deduce it from URL in DESCRIPTION?

**Comment by cboettig** [comment]
Ah, to deduce `isPartOf` from the DESCRIPTION URL?  I guess that is appropriate for rOpenSci (and probably some other cases), but I think it is preferable to have it declared explicitly using the CRAN-approved `X-schema.org-isPartOf` metadata(?)

**Comment by maelle** [comment]
In the case of rOpenSci one could then automatically write this in DESCRIPTION (when not already done) with a message i.e write_codemeta would change DESCRIPTION when the URL is github.com/ropensci/blabla and say that it does? 

And I'd write the recommendation to actively add the field in DESCRIPTION in the bookdown + in the rodev helper https://github.com/ropenscilabs/dev_guide & https://github.com/ropenscilabs/rodev but I'm thinking of all existing pkgs +how to limit authors efforts ☺

**Comment by maelle** [comment]
To be done in `rodev`
