### ISSUE TITLE
Add docs website as relatedLink?

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#67]
E.g. if a package has a pkgdown website, how should this info be saved?

**Comment by maelle** [comment]
I see it's currently added via a codemeta term which I think is a bit more work than having two URLs separated by a comma under URL.

I think that pkgdown needs all URLS to be in URL to link other pkgdown websites from a pkgdown website properly? http://enpiar.com/2017/11/21/getting-down-with-pkgdown/

**Comment by cboettig** [comment]
good call, listing these all in URL field is probably the right thing.

**Comment by maelle** [comment]
It's just a bit sad that CRAN only has one URL field (vs codemeta different terms of codeRepository and relatedLink) because it means the role of an URL will need to be guessed. 😿

**Comment by maelle** [comment]
Done now in dev actually, although I guess that the way I decide whether an URL is codeRepository might be improved.
