### ISSUE TITLE
check URLs

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#68]
I'll close this if I realize the package already tries to navigate to URLs 👼 

If it doesn't yet there could be a warning if an URL seems invalid.

**Comment by maelle** [comment]
```r
get_url_resp <- function(url){
  resp <- httr::GET("https://github.com/ropensci/codemetar")
  httr::status_code(resp)
}
```

maybe only outputting a warning if the code is not 200, not an error, and giving the code (and its explanation via https://github.com/ropensci/fauxpas ?) 🤔

**Comment by cboettig** [comment]
👍 could look at whatever CRAN is using to  check URLs too... though `crul` is probably more sensible

**Comment by maelle** [comment]
For now only the URLs in DESCRIPTION are checked but there could be more checks later.

I added them to `give_opinions`. Maybe/probably not a good function name but I thought that warnings were useless because I imagine there are two scenarios:

* You create codemeta.json for a package you can control, in which case seeing the output of `give_opinions` from `create_codemeta` with verbose=TRUE, or calling `give_opinions` directly, makes sense.

* You create codemeta.json for say all CRAN packages, in which case knowing what to fix is probably not useful, you can't replace URL with good URLs.
