### ISSUE TITLE
URLs in person 

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#74]
cf #64 

Should codemeta.json contain an URL for any authors that has one in comment (in particular for funders)?

**Comment by cboettig** [comment]
yeah, good questions. 

For funders we might want to support DOIs from FundRef (as Zenodo and CrossRef are starting to do, see https://github.com/ropensci/codemetar/blob/master/inst/extdata/funderNames.csv), analgous to what we do with ORCIDs for people.  

For people, url might be nice but also could be stale; I'm happy with ORCID for the moment. (ideally from your ORCID I should be able to get a link to said person's website...)
