### ISSUE TITLE
Separate opinions from the rest

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#76]
@cboettig here are my thoughts :-)

* Have a function `opinionated_codemeta_preparation` or something like that returning a data.frame or list of things that could be improved if following e.g. the guidelines we have at rOpenSci onboarding (using Authors@R, URL in DESCRIPTION etc). Export it.

* In write_codemeta, have an argument `show_opinions` TRUE by default. `create_codemeta` would use the robust codemeta creating code, but `write_codemeta` would also message or warning the data.frame of potential improvements by calling the opinionated function.

* The user could silence this by setting `show_opinions` to FALSE.

* When trying to improve the metadata of a package or of a herd of packages (e.g. all rOpenSci packages) one could use the output of the opinionated function.

**Comment by maelle** [comment]
Function that does that added to dev, and robust author parsing added back.

**Comment by katrinleinweber** [comment]
Because of the discussion in #57, I came to wonder whether this functionality of `codemetar` was considered for inclusion in https://github.com/MangoTheCat/goodpractice/issues/111 for example?

**Comment by maelle** [comment]
Might be worth opening an issue there!
