### ISSUE TITLE
Useless test?

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#78]
@cboettig [this test](https://github.com/ropensci/codemetar/blob/master/tests/testthat/test-write_codemeta.R#L54) seems to be out of place because there are tests for codemeta_description itself.

The test also says there should be a warning when overwriting a file, which is actually not the case?

Could I delete this test if I make sure codemeta_description tests cover both Authors and Maintainer when there is no Authors@R?

**Comment by maelle** [comment]
[current tests in dev](https://github.com/ropensci/codemetar/blob/dev/tests/testthat/test-codemeta_description.R#L16) 

they ensure the "plain" author fields can be parsed and also that the maintainer isn't duplicated.

**Comment by cboettig** [comment]
👍 the tests in `dev` to make sure we can do 'plain' versions as well look good.

**Comment by maelle** [comment]
Cool thanks
