### ISSUE TITLE
Add helper to add affiliation to codemeta.json

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#85]
Related to https://github.com/ropensci/codemetar/issues/83#issuecomment-380814855

I'd be happy to help with [this](https://github.com/ropensci/codemetar/blob/194cf7e97dfdf810465eaae0dca9388c749a4579/R/guess_metadata.R#L87) but I'm actually quite suspicious of the affiliation guessing. I don't think one can guess affiliation from anything external to the package, affiliation is really package-dependent in my opinion. E.g. you can work on a package as part of your job and on another as part of contractor work / as hobby.

**Comment by cboettig** [comment]
fair point.  ideally affiliation would be part of a `person` description, but as you know, I'm a bit loathe to just overload the `comment` field.  

Maybe we should include some utilities that would make it easy to add additional information like this to the `codemeta.json` that simply wasn't in the DESCRIPTION?

**Comment by maelle** [comment]
either that or hoping that `person` could get an affiliation field. 😉 

I wonder where the information could live. If you put your affiliation as cph or fnd it is in the package DESCRIPTION, just not linked to you. Is that an issue? Or is it sufficient to have the affiliation without the link to the person?

**Comment by cboettig** [comment]
sorry, not sure I follow.  I think of `cph` or `fnd` as "roles" not "affiliations", I think of `affiliation` as in http://schema.org/affiliation, i.e. an Organization (university, company); usually the employer.

**Comment by cboettig** [comment]
ah, I get what you mean now, yeah, that makes total sense!

Yeah, this is all very natural to express in `codemeta.json`, e.g. just list the organization id (a URI, e.g. the organization URL) as affiliation of said person; but it's hard to do in DESCRIPTION and maybe not worth hacking there.  Might be better to provide a helper function to just let this live in `codemeta.json`?  

Affiliation could just be a helpful if not particularly important piece of metadata about authors (e.g. Scott once asked, how many rOpenSci contributors have government, academic, or industry affiliations, respectively?)    Affiliation is commonly listed in publication metadata (usually with those pesky footnotes), so it's a common thing to track.  but not super important for most use cases.

**Comment by maelle** [comment]
Some thoughts on this @cboettig 

The helper should be able to read affiliation info from a codemeta.yaml or so. I mean the author shouldn't call the helper themselves after using `create_codemeta` to create/update codemeta.json; instead the helper would be called by `create_codemeta` and would read info that can't live in the README or DESCRIPTION (but maybe affiliation could live in DESCRIPTION using schema terms? 🤔 ).

An example using `rorcid` new function cf #90 would show how to create the codemeta/affiliations.yaml using ORCID.

**Comment by maelle** [comment]
Is adding affiliation via e.g. ORCID ID still something you want to do @cboettig? I wonder whether it is out of scope for `codemetar`.

**Comment by cboettig** [comment]
Agreed.  I think your recent PR to desc basically takes care of this.

**Comment by maelle** [comment]
Now we "just" need to promote ORCID ID use 😉
