### ISSUE TITLE
Fix bug in crosswalk() for upcoming jsonld package release

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#88]
New release of the `jsonld` package exposed a bug in the crosswalk function in the GitHub example.  

GitHub uses integers in the `id` field, which we map to `schema:identifier`.  These need to be coerced to strings first or they cannot compact, since an integer is not a valid type for `identifier` (which expects text or a URL).  

Thanks @jeroen for flagging this, and for  the `jsonld` package update!

**Comment by cboettig** [comment]
@maelle meant to mention explicitly: this means that the upcoming `jsonld` release will break the current CRAN release of `codemetar`, since it will cause the `crosswalk()` unit test to start failing.  So we should fix this and plan on a CRAN release in the near future.  Wanted to flag you on that so we could start strategizing now what changes we want to ship with that release soon soon and what we want to hold off on for a bit longer.  thoughts?

**Comment by maelle** [comment]
Fixed in https://travis-ci.org/ropensci/codemetar/builds/368071585 

The Travis config will have to changed once jsonld has been released cf #91
