### ISSUE TITLE
Replace write_json copy with jsonlite::write_json when jsonlite 1.6 on CRAN

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#94]
https://ci.appveyor.com/project/cboettig/codemetar/build/1.0.190/job/rkuh7k3mbxbatib9

Tests passing locally on Windows so ⁉️

**Comment by cboettig** [comment]
Looks like a UTF-8 issue from the Appveyor error log:

```
1. Error: we can validate this file (@test-codemeta_validate.R#5)  ----------
lexical error: invalid bytes in UTF8 string.
          on",        "givenName": "Ma�lle",        "familyName": "Sal
                     (right here) ------^
```

🤔

**Comment by maelle** [comment]
Yeah i was quite certain i was the issue 😂 will investigate more tomorrow

**Comment by maelle** [comment]
So it passed on my laptop because I had the dev version of `jsonlite`, thanks @jeroen for reminding me that `jsonlite` dev version solves the encoding bug that _I_ had found https://github.com/jeroen/jsonlite/issues/226 :joy:

@jeroen will `jsonlite` soon be released to CRAN? `codemetar` needs to be released to CRAN not too long after `jsonld` because of #88

**Comment by jeroen** [comment]
Maybe you can temporarily include a copy if the fixed function `jsonlite::write_json`? It is only 2 lines.

**Comment by maelle** [comment]
Ok will do thanks
