### ISSUE TITLE
update contributor list

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#95]
@maelle can you make yourself into role `aut` on the package and add other contributors listed on https://github.com/ropensci/codemetar/graphs/contributors as `ctb`?

**Comment by maelle** [comment]
Yay, a promotion! Will do tomorrow, maybe writing a helper in `ghrecipes` for the ctbs

**Comment by maelle** [comment]
@katrinleinweber, @arfon, @annakrystalli, @noamross are you ok with being added to DESCRIPTION as `ctb`? (`ctb` _and_ `rev`, Anna)

**Comment by noamross** [comment]
👍

**Comment by arfon** [comment]
👍

**Comment by katrinleinweber** [comment]
:+1: Thank you :-)

**Comment by maelle** [comment]
Thanks everyone for your answer, you were added to DESCRIPTION in the soon-to-be-merged dev branch.

Code in https://gist.github.com/maelle/75261a0b6793d18cfdd02734d2e3f243
