### ISSUE TITLE
How to have several relatedLinks and several contIntegrations

### ISSUE THREAD

**Issue by maelle** [ropensci/codemetar#99]
@cboettig I'd like to add a function `add_related_link` that'd take a `cm` object and an URL as arguments, that'd add the relatedLink to the codemeta without deleting previous relatedLinks. At the beginning of codemeta creation, relatedLinks would be removed but there could be the case where one adds both a pkgdown link cf #67 and a CRAN link cf #81 

I have two questions

* I do not know how the list should be formatted for the codemeta to then be valid in case there are several relatedLinks.

* Is it actually ok to have several relatedLinks reg the codemeta standard?

**Comment by maelle** [comment]
I've just renamed the issue because I have the exact same question for continuous integration, since there's no reason to have only one link and not all of them e.g. Appveyor as well for this repo.

**Comment by cboettig** [comment]
yes, any field (except `@id`) in codemeta (or JSON-LD in general) can be list valued; e.g. `"relatedLinks": ["http://example.com/", "http://example.com/2"]`

**Comment by maelle** [comment]
cool, will add some tests then.

**Comment by maelle** [comment]
Ok done via https://github.com/ropensci/codemetar/pull/108

Now codemeta.json for `codemetar` itself has its CRAN and pkgdown URLs as relatedLinks 🎊
